"""make client and marchant registered_by field to nullable

Revision ID: b3eada959c96
Revises: b20143d55f6f
Create Date: 2024-12-16 05:17:35.586726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3eada959c96'
down_revision: Union[str, None] = 'b20143d55f6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'registered_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('merchants', 'registered_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('merchants', 'registered_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('clients', 'registered_by',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
