"""Initial migration

Revision ID: a461be6ca2b9
Revises: 
Create Date: 2024-09-16 06:17:30.123382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a461be6ca2b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_operations_id', table_name='operations')
    op.drop_table('operations')
    op.drop_index('ix_ussd_sessions_id', table_name='ussd_sessions')
    op.drop_index('ix_ussd_sessions_phone_number', table_name='ussd_sessions')
    op.drop_index('ix_ussd_sessions_session_id', table_name='ussd_sessions')
    op.drop_table('ussd_sessions')
    op.drop_index('ix_clients_address', table_name='clients')
    op.drop_index('ix_clients_balance', table_name='clients')
    op.drop_index('ix_clients_email', table_name='clients')
    op.drop_index('ix_clients_id', table_name='clients')
    op.drop_index('ix_clients_market_code', table_name='clients')
    op.drop_index('ix_clients_phone_number', table_name='clients')
    op.drop_index('ix_clients_pin', table_name='clients')
    op.drop_index('ix_clients_status', table_name='clients')
    op.drop_index('ix_clients_type', table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('pin', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('balance', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('market_code', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sponsor', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_clients_type', 'clients', ['type'], unique=False)
    op.create_index('ix_clients_status', 'clients', ['status'], unique=False)
    op.create_index('ix_clients_pin', 'clients', ['pin'], unique=False)
    op.create_index('ix_clients_phone_number', 'clients', ['phone_number'], unique=True)
    op.create_index('ix_clients_market_code', 'clients', ['market_code'], unique=False)
    op.create_index('ix_clients_id', 'clients', ['id'], unique=False)
    op.create_index('ix_clients_email', 'clients', ['email'], unique=True)
    op.create_index('ix_clients_balance', 'clients', ['balance'], unique=False)
    op.create_index('ix_clients_address', 'clients', ['address'], unique=False)
    op.create_table('ussd_sessions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('data', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_ussd_sessions_session_id', 'ussd_sessions', ['session_id'], unique=True)
    op.create_index('ix_ussd_sessions_phone_number', 'ussd_sessions', ['phone_number'], unique=False)
    op.create_index('ix_ussd_sessions_id', 'ussd_sessions', ['id'], unique=False)
    op.create_table('operations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('client_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('target_phone', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=True),
    sa.Column('fees', mysql.FLOAT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name='operations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_operations_id', 'operations', ['id'], unique=False)
    # ### end Alembic commands ###
